name: Generate Statistics About The Recent Commit

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs: 
  generate-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate commit status
      run: |
        echo "Latest Commit Stats" > repo-stats.txt
        echo echo "===================" >> repo-stats.txt
        echo "Date: $(date)" >> repo-stats.txt
        echo "Committer: ${{ github.event.pusher.name }}" >> repo-stats.txt
        echo "Committer Email: ${{ github.event.pusher.email }}" >> repo-stats.txt
        echo "Commit SHA: ${{ github.sha }}" >> repo-stats.txt
        echo "Commit Message: ${{ github.event.head_commit.message }}" >> repo-stats.txt
        echo "Branch: ${{ github.ref_name }}" >> repo-stats.txt
        cat repo-stats.txt

    - name: Commit stats file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add repo-stats.txt
        git commit -m "Update stats file" -a || echo "No changes to commit"
        git push

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
